[package]
name = "folder-find"
version = "0.4.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
clap_complete = { version = "4.5.40" }
rayon = "1.11.0"
colour = "2.1.0"
